### ISSUE TITLE
Is it possible to install this plugin within Eclipse?

### ISSUE THREAD

**Issue by seekM** [xmolecules/jmolecules-eclipse-plugin#40]
Is it possible to install this plugin within Eclipse via "Help > Install New Software..."?

**Comment by naturzukunft** [comment]
Clone the project and build it with maven and java 11.
Open Eclipse and navigate to
Help->install new software->Add->Archive->(1)->Add

(1).../jmolecules-eclipse-plugin/org.jmolecules.eclipse.updatesite/target/org.jmolecules.eclipse.updatesite-1.0.0-SNAPSHOT.zip

worked for me. 
Using:
Spring Tool Suite 4 
Version: 4.15.3.RELEASE
Build Id: 202208110744

**Comment by seekM** [comment]
Thank you for the help!
